<section class="formStyle">
 
 <h1>Connexion</h1>
 
<!-- form pour se connecter -->
 <form action="index.php?route=seConnecte" method="POST">
     
            <input class="input" placeholder="Email" type="email" name="email" id="email" required />
            <input class="input" placeholder="Mot de passe" type="password" name="password" id="password" required/>
            <!-- button se connecte -->
            <div class="main__btn"><input  class="in__btn" name="submit" type="submit" value="Se connecter"/></div>
            
            
        </div>
</form>

</section>