<!-- form pour contacter -->

<section class="formStyle">
    
    <h1>Contact</h1>
    
        <form action="index.php?route=contactSubmit" method="POST">
            
            <input class="input" type="text" name="name" placeholder="Nom" required/>
            
            <input class="input" type="email" name="email" placeholder="Email"required/>
            
            <textarea class="input" type="text" name="message" placeholder="Message" required/></textarea>
            
            <div class="main__btn"><input  class="in__btn" type="submit" value="Envoyer"/></div>
            
        </form>
        
</section>